core.py update to avoid AttributeError
Updated core.py to avoid
AttributeError: module 'collections' has no attribute 'Callable'
when running show_hids.py example with python 3.10
https://github.com/rene-aguirre/pywinusb/blob/master/examples/show_hids.py